Document: openrecipes
Title: Debian openrecipes Manual
Author: <insert document author here>
Abstract: This manual describes what openrecipes is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openrecipes/openrecipes.sgml.gz

Format: postscript
Files: /usr/share/doc/openrecipes/openrecipes.ps.gz

Format: text
Files: /usr/share/doc/openrecipes/openrecipes.text.gz

Format: HTML
Index: /usr/share/doc/openrecipes/html/index.html
Files: /usr/share/doc/openrecipes/html/*.html
